//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagement_proj.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HealthCareClinicDB_T2Entities : DbContext
    {
        public HealthCareClinicDB_T2Entities()
            : base("name=HealthCareClinicDB_T2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Audit_Appointment> Audit_Appointment { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<DoctorSchedule> DoctorSchedules { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Specialty> Specialties { get; set; }
        public virtual DbSet<TimeSlot> TimeSlots { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<vw_DoctorTodaySchedule> vw_DoctorTodaySchedule { get; set; }
        public virtual DbSet<vw_PatientClinicalSummary> vw_PatientClinicalSummary { get; set; }
        public virtual DbSet<vw_PatientRecordsSummary> vw_PatientRecordsSummary { get; set; }
        public virtual DbSet<vw_UpcomingAppointments> vw_UpcomingAppointments { get; set; }
    
        public virtual ObjectResult<sp_GetAvailableSlots_Result> sp_GetAvailableSlots(Nullable<int> doctorId, Nullable<System.DateTime> date)
        {
            var doctorIdParameter = doctorId.HasValue ?
                new ObjectParameter("DoctorId", doctorId) :
                new ObjectParameter("DoctorId", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAvailableSlots_Result>("sp_GetAvailableSlots", doctorIdParameter, dateParameter);
        }
    }
}
