//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagement_proj.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Id { get; set; }
        public int DoctorId { get; set; }
        public string Schedule1 { get; set; }
        public System.DateTime EffectiveDate { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
