//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagement_proj.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UpcomingAppointments
    {
        public int AppointmentId { get; set; }
        public string PatientName { get; set; }
        public string PhoneNumber { get; set; }
        public string DoctorName { get; set; }
        public string Specialization { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public int Duration { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public int PatientId { get; set; }
        public int DoctorId { get; set; }
    }
}
